/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/capture-sops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCaptureSOPs"];
        put?: never;
        post: operations["createCaptureSOP"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capture-sops/{sop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sop_id: components["parameters"]["SOPID"];
            };
            cookie?: never;
        };
        get: operations["getCaptureSOP"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capture-sops/{sop_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sop_id: components["parameters"]["SOPID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["copySOPVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sop-versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        get: operations["getSOPVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSOPVersion"];
        trace?: never;
    };
    "/sop-versions/{version_id}/views": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addSOPView"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sop-versions/{version_id}/views/{view_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSOPView"];
        options?: never;
        head?: never;
        patch: operations["updateSOPView"];
        trace?: never;
    };
    "/sop-versions/{version_id}/view-order": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["reorderSOPViews"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sop-versions/{version_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateSOPVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sop-versions/{version_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishSOPVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sop-versions/{version_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archiveSOPVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sop-versions/{version_id}/views/{view_id}/reference-images/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSOPReferenceUploadURL"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sop-versions/{version_id}/views/{view_id}/reference-images": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addSOPReferenceImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sop-versions/{version_id}/views/{view_id}/reference-images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
                image_id: components["parameters"]["ImageID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSOPReferenceImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sop-versions/{version_id}/views/{view_id}/reference-image-order": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["reorderSOPReferenceImages"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photo-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPhotoSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAssetUploadURL"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeAssetUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAssetsForReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/review/hierarchy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAssetReviewHierarchy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LocalizedText: {
            "zh-CN": string;
            en: string;
        };
        Vector3: number[];
        Composition: {
            frame_occupancy: number;
            aspect_ratio: string;
            allow_rotation_correction: boolean;
            /** @enum {boolean} */
            allow_mirror: false;
        };
        Pose: {
            /** @enum {string} */
            space: "object";
            camera_position_direction: components["schemas"]["Vector3"];
            image_up_direction: components["schemas"]["Vector3"];
            target: components["schemas"]["Vector3"];
        };
        ReferenceImage: {
            /** Format: uuid */
            public_id: string;
            object_key: string;
            thumbnail_url: string;
            sort_order: number;
            caption: components["schemas"]["LocalizedText"];
            /** Format: date-time */
            created_at?: string;
        };
        SOPView: {
            /** Format: uuid */
            public_id: string;
            sequence: number;
            /** @enum {string} */
            role: "reference_front" | "capture";
            /** @enum {string} */
            view_kind: "standard" | "detail";
            preset_key?: string;
            name: components["schemas"]["LocalizedText"];
            instruction: components["schemas"]["LocalizedText"];
            required: boolean;
            pose: components["schemas"]["Pose"];
            composition: components["schemas"]["Composition"];
            reference_images: components["schemas"]["ReferenceImage"][];
        };
        CoordinateSystem: {
            /** @enum {string} */
            id: "pcs_object_v1";
            /** @enum {string} */
            handedness: "right_handed";
            /** @enum {string} */
            origin: "bounding_box_center";
            /** @enum {string} */
            unit: "normalized";
            axes: {
                /** @enum {string} */
                x_positive: "object_top";
                /** @enum {string} */
                y_positive: "object_left";
                /** @enum {string} */
                z_positive: "object_front";
            };
        };
        SOPVersion: {
            /** @enum {string} */
            schema_version: "1.0";
            /** Format: uuid */
            public_id: string;
            /** Format: uuid */
            sop_public_id: string;
            version_number: number;
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            name: components["schemas"]["LocalizedText"];
            description: components["schemas"]["LocalizedText"];
            coordinate_system: components["schemas"]["CoordinateSystem"];
            /** Format: date-time */
            published_at?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            views: components["schemas"]["SOPView"][];
        };
        CaptureSOPSummary: {
            /** Format: uuid */
            public_id: string;
            category_id: number;
            versions: components["schemas"]["SOPVersion"][];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ViewMutation: {
            /** @enum {string} */
            role: "reference_front" | "capture";
            /** @enum {string} */
            view_kind: "standard" | "detail";
            name: components["schemas"]["LocalizedText"];
            instruction: components["schemas"]["LocalizedText"];
            required: boolean;
            pose: components["schemas"]["Pose"];
            composition: components["schemas"]["Composition"];
        };
        AddViewRequest: {
            /** @enum {string} */
            preset_key?: "back" | "left" | "bottom" | "right" | "top" | "detail_label" | "packaging_front";
            custom?: components["schemas"]["ViewMutation"];
        } & (unknown | unknown);
        CreateCaptureSOPRequest: {
            category_id: number;
            name: components["schemas"]["LocalizedText"];
            description?: components["schemas"]["LocalizedText"];
        };
        VersionMetadataRequest: {
            name: components["schemas"]["LocalizedText"];
            description: components["schemas"]["LocalizedText"];
        };
        AddReferenceImageRequest: {
            object_key: string;
            thumbnail_url: string;
            caption: components["schemas"]["LocalizedText"];
            sort_order?: number;
        };
        ValidationError: {
            code: string;
            path: string;
            message: components["schemas"]["LocalizedText"];
        };
        ValidationResponse: {
            /** @enum {string} */
            code: "sop_valid" | "sop_validation_failed";
            errors: components["schemas"]["ValidationError"][];
        };
        ErrorResponse: {
            code: string;
            message: string;
        };
        AuthErrorResponse: {
            message: string;
        };
        UploadEnvelope: {
            /** @enum {string} */
            method: "PUT";
            /** Format: uri */
            upload_url: string;
            /** Format: uri */
            asset_url: string;
            object_key: string;
            expires_in: number;
            headers: {
                [key: string]: string;
            };
        };
        CreatePhotoSessionRequest: {
            sku_id: number;
            /** Format: uuid */
            sop_version_id: string;
        };
        PhotoSession: {
            /** Format: uuid */
            public_id: string;
            code: string;
            sku_id: number;
            /** Format: uuid */
            sop_version_id: string;
            /** @enum {string} */
            status: "in_progress" | "completed";
            /** Format: date-time */
            created_at: string;
        };
        CreateAssetUploadRequest: {
            file_name: string;
            content_type: string;
            /** Format: uuid */
            photo_session_id: string;
            /** Format: uuid */
            sop_view_id: string;
        };
        CompleteAssetRequest: {
            /** Format: uuid */
            photo_session_id: string;
            /** Format: uuid */
            sop_view_id: string;
            object_key: string;
            original_url: string;
            thumbnail_url?: string;
            /** Format: date-time */
            captured_at?: string;
        };
        CompletedAsset: {
            id: number;
            sku_id: number;
            /** Format: uuid */
            photo_session_id: string;
            /** Format: uuid */
            sop_view_id: string;
            object_key: string;
            original_url: string;
            thumbnail_url: string;
            /** @enum {string} */
            review_status: "pending" | "approved" | "rejected";
            /** Format: date-time */
            captured_at: string;
        };
        AssetReviewItem: {
            id: number;
            sku_id: number;
            original_url: string;
            thumbnail_url: string;
            /** @enum {string} */
            review_status: "pending" | "approved" | "rejected";
            /** Format: date-time */
            captured_at: string;
            sop_view_name: components["schemas"]["LocalizedText"];
            photo_session_code: string;
        };
        Tag: {
            id: number;
            name: string;
        };
        AssetReviewSKU: {
            id: number;
            code: string;
            product_name: string;
            tags: components["schemas"]["Tag"][];
            assets: components["schemas"]["AssetReviewHierarchyAsset"][];
        };
        AssetReviewHierarchyAsset: {
            id: number;
            original_url: string;
            thumbnail_url: string;
            /** @enum {string} */
            review_status: "pending" | "approved" | "rejected";
            /** Format: date-time */
            captured_at: string;
            sop_view_name: components["schemas"]["LocalizedText"];
            photo_session_code: string;
        };
        AssetReviewCategory: {
            id: number;
            name: string;
            name_en: string;
            is_system: boolean;
            skus: components["schemas"]["AssetReviewSKU"][];
        };
    };
    responses: {
        /** @description Invalid input */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing or invalid bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuthErrorResponse"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Lifecycle conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description SOP aggregate validation failed */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationResponse"];
            };
        };
        /** @description Unexpected database or server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Object storage unavailable */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        SOPID: string;
        VersionID: string;
        ViewID: string;
        ImageID: string;
    };
    requestBodies: {
        UUIDOrder: {
            content: {
                "application/json": {
                    public_ids: string[];
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCaptureSOPs: {
        parameters: {
            query?: {
                category_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capture SOPs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CaptureSOPSummary"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createCaptureSOP: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCaptureSOPRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCaptureSOP: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sop_id: components["parameters"]["SOPID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capture SOP */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureSOPSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    copySOPVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sop_id: components["parameters"]["SOPID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    source_version_id: string;
                };
            };
        };
        responses: {
            /** @description Copied draft */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getSOPVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SOP version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateSOPVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionMetadataRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    addSOPView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddViewRequest"];
            };
        };
        responses: {
            /** @description View added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteSOPView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateSOPView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewMutation"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    reorderSOPViews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UUIDOrder"];
        responses: {
            /** @description Reordered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    validateSOPVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    publishSOPVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalServerError"];
        };
    };
    archiveSOPVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createSOPReferenceUploadURL: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    file_name: string;
                    content_type: string;
                };
            };
        };
        responses: {
            /** @description Upload details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    addSOPReferenceImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddReferenceImageRequest"];
            };
        };
        responses: {
            /** @description Reference image */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceImage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteSOPReferenceImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
                image_id: components["parameters"]["ImageID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    reorderSOPReferenceImages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UUIDOrder"];
        responses: {
            /** @description Reordered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createPhotoSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePhotoSessionRequest"];
            };
        };
        responses: {
            /** @description Photo session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createAssetUploadURL: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssetUploadRequest"];
            };
        };
        responses: {
            /** @description Upload details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    completeAssetUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteAssetRequest"];
            };
        };
        responses: {
            /** @description Asset completed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedAsset"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listAssetsForReview: {
        parameters: {
            query?: {
                status?: "pending" | "approved" | "rejected";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review assets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AssetReviewItem"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listAssetReviewHierarchy: {
        parameters: {
            query?: {
                status?: "pending" | "approved" | "rejected";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review assets grouped by category and SKU */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AssetReviewCategory"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
