/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/capture-sops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCaptureSOPs"];
        put?: never;
        post: operations["createCaptureSOP"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capture-sops/{sop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sop_id: components["parameters"]["SOPID"];
            };
            cookie?: never;
        };
        get: operations["getCaptureSOP"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capture-sops/{sop_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sop_id: components["parameters"]["SOPID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["copySOPVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sop-versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        get: operations["getSOPVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSOPVersion"];
        trace?: never;
    };
    "/sop-versions/{version_id}/views": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addSOPView"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sop-versions/{version_id}/views/{view_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSOPView"];
        options?: never;
        head?: never;
        patch: operations["updateSOPView"];
        trace?: never;
    };
    "/sop-versions/{version_id}/view-order": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["reorderSOPViews"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sop-versions/{version_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateSOPVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sop-versions/{version_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishSOPVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sop-versions/{version_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archiveSOPVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sop-versions/{version_id}/views/{view_id}/reference-images/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSOPReferenceUploadURL"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sop-versions/{version_id}/views/{view_id}/reference-images": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addSOPReferenceImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sop-versions/{version_id}/views/{view_id}/reference-images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
                image_id: components["parameters"]["ImageID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSOPReferenceImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sop-versions/{version_id}/views/{view_id}/reference-image-order": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["reorderSOPReferenceImages"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photo-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPhotoSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAssetUploadURL"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeAssetUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAssetsForReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/review/hierarchy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAssetReviewHierarchy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/openai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOpenAISetting"];
        put: operations["putOpenAISetting"];
        post?: never;
        delete: operations["disableOpenAISetting"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai-content-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAIContentTemplates"];
        put?: never;
        post: operations["createAIContentTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai-content-templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: components["parameters"]["AIContentTemplateID"];
            };
            cookie?: never;
        };
        get: operations["getAIContentTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai-content-templates/{template_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: components["parameters"]["AIContentTemplateID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["copyAIContentTemplateVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai-content-template-versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["AIContentTemplateVersionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAIContentTemplateVersion"];
        trace?: never;
    };
    "/ai-content-template-versions/{version_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["AIContentTemplateVersionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateAIContentTemplateVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai-content-template-versions/{version_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["AIContentTemplateVersionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishAIContentTemplateVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai-content-template-versions/{version_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["AIContentTemplateVersionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archiveAIContentTemplateVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAIJobs"];
        put?: never;
        post: operations["createAIJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["AIJobID"];
            };
            cookie?: never;
        };
        get: operations["getAIJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OpenAISetting: {
            /** @enum {string} */
            provider: "openai";
            /** @enum {string} */
            status: "unconfigured" | "active" | "invalid" | "disabled";
            /** @description Non-secret display fingerprint; empty when unconfigured. */
            key_fingerprint: string;
            /** Format: date-time */
            verified_at: string | null;
            /** Format: date-time */
            image_capability_verified_at: string | null;
            /** Format: date-time */
            last_used_at: string | null;
        };
        OpenAISettingRequest: {
            /** Format: password */
            api_key: string;
        };
        AIContentSlotMutation: {
            slot_key?: string;
            /** @enum {string} */
            kind?: "image" | "title" | "seo_description";
            name_zh?: string;
            name_en?: string;
            description_zh?: string;
            description_en?: string;
            sequence?: number;
            optional?: boolean;
            default_selected?: boolean;
            prompt_fragment?: string;
            constraints?: unknown;
            generation_config?: unknown;
            layout_config?: unknown;
        };
        AIContentTemplateMutationRequest: {
            name_zh?: string;
            name_en?: string;
            target_platform?: string;
            default_locale?: string;
            prompt_compiler_version?: string;
            platform_prompt?: string;
            slots?: components["schemas"]["AIContentSlotMutation"][];
        };
        CopyAIContentTemplateVersionRequest: {
            /** Format: uuid */
            source_version_id: string;
        };
        AIContentSlot: {
            /** Format: uuid */
            public_id: string;
            slot_key: string;
            /** @enum {string} */
            kind: "image" | "title" | "seo_description";
            name_zh: string;
            name_en: string;
            description_zh: string;
            description_en: string;
            sequence: number;
            optional: boolean;
            default_selected: boolean;
            prompt_fragment: string;
            constraints: unknown;
            generation_config: unknown;
            layout_config: unknown;
        };
        AIContentTemplateVersion: {
            /** Format: uuid */
            public_id: string;
            version_number: number;
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            default_locale: string;
            prompt_compiler_version: string;
            platform_prompt: string;
            /** Format: date-time */
            published_at: string | null;
            /** Format: date-time */
            archived_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            slots: components["schemas"]["AIContentSlot"][];
        };
        AIContentTemplate: {
            /** Format: uuid */
            public_id: string;
            name_zh: string;
            name_en: string;
            target_platform: string;
            /** @enum {string} */
            status: "active" | "archived";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            versions: components["schemas"]["AIContentTemplateVersion"][];
        };
        CreateAIJobRequest: {
            sku_id: number;
            /** Format: uuid */
            template_version_id: string;
            selected_slot_keys: string[];
            /** @description Duplicate IDs are accepted and normalized to one ordered reference. */
            selected_asset_ids: number[];
            locale: string;
            /** @description Optional L4 user instruction stored immutably in the job snapshot. */
            user_preference?: string;
            /** @description Per-selected-slot overrides; each supplied value must appear in the published slot's matching allowed_* array. */
            generation_overrides?: {
                [key: string]: components["schemas"]["AIJobGenerationOverride"];
            };
        };
        AIJobGenerationOverride: {
            candidate_count?: number;
            size?: string;
            quality?: string;
            style?: string;
        };
        AIJob: {
            /** Format: uuid */
            public_id: string;
            sku_id: number;
            /** Format: uuid */
            template_version_id: string;
            target_platform: string;
            locale: string;
            /** @enum {string} */
            status: "queued" | "running" | "partial" | "completed" | "failed" | "cancelled";
            /** @enum {string} */
            snapshot_schema: "cargoflow_product_generation_v1";
            input_snapshot: components["schemas"]["ProductSnapshotV1"];
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            completed_at: string | null;
            /** Format: date-time */
            cancelled_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            items: components["schemas"]["AIJobItem"][];
        };
        AIJobItem: {
            /** Format: uuid */
            public_id: string;
            slot_key: string;
            /** @enum {string} */
            kind: "image" | "title" | "seo_description";
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "failed" | "cancelled";
            slot_snapshot: components["schemas"]["AIJobSlotSnapshot"];
            selected_input_asset_ids: number[];
            attempt_count: number;
            safe_error: string;
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            completed_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AIJobSlotSnapshot: {
            /** Format: uuid */
            public_id: string;
            slot_key: string;
            /** @enum {string} */
            kind: "image" | "title" | "seo_description";
            name: components["schemas"]["AISnapshotLocalizedText"];
            description: components["schemas"]["AISnapshotLocalizedText"];
            sequence: number;
            optional: boolean;
            default_selected: boolean;
            prompt_fragment: string;
            constraints: {
                [key: string]: unknown;
            };
            generation_config: {
                [key: string]: unknown;
            };
            layout_config: {
                [key: string]: unknown;
            };
        };
        AISnapshotLocalizedText: {
            zh: string;
            en: string;
        };
        AISnapshotVector: {
            x: number;
            y: number;
            z: number;
        };
        AISnapshotCategory: {
            name_zh: string;
            name_en: string;
        };
        AISnapshotProduct: {
            name: string;
            brand: string;
            description: string;
            category: components["schemas"]["AISnapshotCategory"];
        };
        AISnapshotSKU: {
            code: string;
            color: string;
            size: string;
            platform_title: string;
            selling_points: string;
            tags: string[];
        };
        AISnapshotSOPView: {
            /** Format: uuid */
            public_id: string;
            sequence: number;
            /** @enum {string} */
            role: "reference_front" | "capture";
            /** @enum {string} */
            view_kind: "standard" | "detail";
            preset_key: string;
            name: components["schemas"]["AISnapshotLocalizedText"];
            instruction: components["schemas"]["AISnapshotLocalizedText"];
            required: boolean;
            camera_position_direction: components["schemas"]["AISnapshotVector"];
            image_up_direction: components["schemas"]["AISnapshotVector"];
            target: components["schemas"]["AISnapshotVector"];
            composition: components["schemas"]["Composition"];
        };
        AISnapshotSOP: {
            /** Format: uuid */
            public_id: string;
            /** Format: uuid */
            version_public_id: string;
            version_number: number;
            schema_version: string;
            name: components["schemas"]["AISnapshotLocalizedText"];
            description: components["schemas"]["AISnapshotLocalizedText"];
            /** @enum {string} */
            coordinate_system: "pcs_object_v1";
            views: components["schemas"]["AISnapshotSOPView"][];
        };
        AISnapshotAssetView: {
            /** Format: uuid */
            public_id: string;
            preset_key: string;
            name: components["schemas"]["AISnapshotLocalizedText"];
            /** @enum {string} */
            role: "reference_front" | "capture";
            /** @enum {string} */
            view_kind: "standard" | "detail";
            instruction: components["schemas"]["AISnapshotLocalizedText"];
            camera_position_direction: components["schemas"]["AISnapshotVector"];
            image_up_direction: components["schemas"]["AISnapshotVector"];
            target: components["schemas"]["AISnapshotVector"];
            composition: components["schemas"]["Composition"];
        };
        AISnapshotAsset: {
            id: number;
            object_key: string;
            /** Format: uri */
            original_url: string;
            thumbnail_url: string;
            /** Format: date-time */
            captured_at: string;
            view: components["schemas"]["AISnapshotAssetView"];
        };
        AISnapshotTemplate: {
            /** Format: uuid */
            template_public_id: string;
            /** Format: uuid */
            version_public_id: string;
            version_number: number;
            prompt_compiler_version: string;
            platform_prompt: string;
            selected_slots: components["schemas"]["AIJobSlotSnapshot"][];
        };
        ProductSnapshotV1: {
            /** @enum {string} */
            schema: "cargoflow_product_generation_v1";
            locale: string;
            target_platform: string;
            product: components["schemas"]["AISnapshotProduct"];
            sku: components["schemas"]["AISnapshotSKU"];
            sop: components["schemas"]["AISnapshotSOP"];
            template: components["schemas"]["AISnapshotTemplate"];
            selected_assets: components["schemas"]["AISnapshotAsset"][];
            user_preference: string;
            generation_overrides: {
                [key: string]: components["schemas"]["AIJobGenerationOverride"];
            };
        };
        AITemplateValidationIssue: {
            code: string;
            path: string;
            message: string;
        };
        AITemplateValidationResponse: {
            /** @enum {string} */
            code: "template_valid" | "template_validation_failed";
            issues: components["schemas"]["AITemplateValidationIssue"][];
        };
        LocalizedText: {
            "zh-CN": string;
            en: string;
        };
        Vector3: number[];
        Composition: {
            frame_occupancy: number;
            aspect_ratio: string;
            allow_rotation_correction: boolean;
            /** @enum {boolean} */
            allow_mirror: false;
        };
        Pose: {
            /** @enum {string} */
            space: "object";
            camera_position_direction: components["schemas"]["Vector3"];
            image_up_direction: components["schemas"]["Vector3"];
            target: components["schemas"]["Vector3"];
        };
        ReferenceImage: {
            /** Format: uuid */
            public_id: string;
            object_key: string;
            thumbnail_url: string;
            sort_order: number;
            caption: components["schemas"]["LocalizedText"];
            /** Format: date-time */
            created_at?: string;
        };
        SOPView: {
            /** Format: uuid */
            public_id: string;
            sequence: number;
            /** @enum {string} */
            role: "reference_front" | "capture";
            /** @enum {string} */
            view_kind: "standard" | "detail";
            preset_key?: string;
            name: components["schemas"]["LocalizedText"];
            instruction: components["schemas"]["LocalizedText"];
            required: boolean;
            pose: components["schemas"]["Pose"];
            composition: components["schemas"]["Composition"];
            reference_images: components["schemas"]["ReferenceImage"][];
        };
        CoordinateSystem: {
            /** @enum {string} */
            id: "pcs_object_v1";
            /** @enum {string} */
            handedness: "right_handed";
            /** @enum {string} */
            origin: "bounding_box_center";
            /** @enum {string} */
            unit: "normalized";
            axes: {
                /** @enum {string} */
                x_positive: "object_top";
                /** @enum {string} */
                y_positive: "object_left";
                /** @enum {string} */
                z_positive: "object_front";
            };
        };
        SOPVersion: {
            /** @enum {string} */
            schema_version: "1.0";
            /** Format: uuid */
            public_id: string;
            /** Format: uuid */
            sop_public_id: string;
            version_number: number;
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            name: components["schemas"]["LocalizedText"];
            description: components["schemas"]["LocalizedText"];
            coordinate_system: components["schemas"]["CoordinateSystem"];
            /** Format: date-time */
            published_at?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at: string;
            views: components["schemas"]["SOPView"][];
        };
        CaptureSOPSummary: {
            /** Format: uuid */
            public_id: string;
            category_id: number;
            versions: components["schemas"]["SOPVersion"][];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ViewMutation: {
            /** @enum {string} */
            role: "reference_front" | "capture";
            /** @enum {string} */
            view_kind: "standard" | "detail";
            name: components["schemas"]["LocalizedText"];
            instruction: components["schemas"]["LocalizedText"];
            required: boolean;
            pose: components["schemas"]["Pose"];
            composition: components["schemas"]["Composition"];
        };
        AddViewRequest: {
            /** @enum {string} */
            preset_key?: "back" | "left" | "bottom" | "right" | "top" | "detail_label" | "packaging_front";
            custom?: components["schemas"]["ViewMutation"];
        } & (unknown | unknown);
        CreateCaptureSOPRequest: {
            category_id: number;
            name: components["schemas"]["LocalizedText"];
            description?: components["schemas"]["LocalizedText"];
        };
        VersionMetadataRequest: {
            name: components["schemas"]["LocalizedText"];
            description: components["schemas"]["LocalizedText"];
        };
        AddReferenceImageRequest: {
            object_key: string;
            thumbnail_url: string;
            caption: components["schemas"]["LocalizedText"];
            sort_order?: number;
        };
        ValidationError: {
            code: string;
            path: string;
            message: components["schemas"]["LocalizedText"];
        };
        ValidationResponse: {
            /** @enum {string} */
            code: "sop_valid" | "sop_validation_failed";
            errors: components["schemas"]["ValidationError"][];
        };
        ErrorResponse: {
            code: string;
            message: string;
        };
        AuthErrorResponse: {
            message: string;
        };
        SOPReferenceUploadEnvelope: {
            /** @enum {string} */
            method: "PUT";
            /** Format: uri */
            upload_url: string;
            /** Format: uri */
            asset_url: string;
            object_key: string;
            expires_in: number;
            headers: {
                [key: string]: string;
            };
        };
        AssetUploadEnvelope: {
            /** @enum {string} */
            method: "PUT";
            /** Format: uri */
            upload_url: string;
            /** Format: uri */
            asset_url: string;
            object_key: string;
            /** @description Short-lived signed ticket required to complete this exact upload. */
            completion_token: string;
            expires_in: number;
            headers: {
                [key: string]: string;
            };
        };
        CreatePhotoSessionRequest: {
            sku_id: number;
            /** Format: uuid */
            sop_version_id: string;
        };
        PhotoSession: {
            /** Format: uuid */
            public_id: string;
            code: string;
            sku_id: number;
            /** Format: uuid */
            sop_version_id: string;
            /** @enum {string} */
            status: "in_progress" | "completed";
            /** Format: date-time */
            created_at: string;
        };
        CreateAssetUploadRequest: {
            file_name: string;
            content_type: string;
            /** Format: uuid */
            photo_session_id: string;
            /** Format: uuid */
            sop_view_id: string;
        };
        CompleteAssetRequest: {
            /** Format: uuid */
            photo_session_id: string;
            /** Format: uuid */
            sop_view_id: string;
            /** @description Signed ticket returned by createAssetUploadURL; binds user, session, view, object key, and expiry. */
            completion_token: string;
            /** Format: date-time */
            captured_at?: string;
        };
        CompletedAsset: {
            id: number;
            sku_id: number;
            /** Format: uuid */
            photo_session_id: string;
            /** Format: uuid */
            sop_view_id: string;
            object_key: string;
            original_url: string;
            thumbnail_url: string;
            /** @enum {string} */
            review_status: "pending" | "approved" | "rejected";
            /** Format: date-time */
            captured_at: string;
        };
        AssetReviewItem: {
            id: number;
            sku_id: number;
            original_url: string;
            thumbnail_url: string;
            /** @enum {string} */
            review_status: "pending" | "approved" | "rejected";
            /** Format: date-time */
            captured_at: string;
            sop_view_name: components["schemas"]["LocalizedText"];
            photo_session_code: string;
        };
        Tag: {
            id: number;
            name: string;
        };
        AssetReviewSKU: {
            id: number;
            code: string;
            product_name: string;
            tags: components["schemas"]["Tag"][];
            assets: components["schemas"]["AssetReviewHierarchyAsset"][];
        };
        AssetReviewHierarchyAsset: {
            id: number;
            original_url: string;
            thumbnail_url: string;
            /** @enum {string} */
            review_status: "pending" | "approved" | "rejected";
            /** Format: date-time */
            captured_at: string;
            sop_view_name: components["schemas"]["LocalizedText"];
            photo_session_code: string;
        };
        AssetReviewCategory: {
            id: number;
            name: string;
            name_en: string;
            is_system: boolean;
            skus: components["schemas"]["AssetReviewSKU"][];
        };
    };
    responses: {
        /** @description Invalid input */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing or invalid bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuthErrorResponse"];
            };
        };
        /** @description Authenticated user lacks the required role */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Lifecycle conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description X-SOP-Version-Updated-At is required for draft aggregate mutations */
        PreconditionRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description SOP aggregate validation failed */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationResponse"];
            };
        };
        /** @description Unexpected database or server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Required service or server dependency unavailable */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        SOPID: string;
        VersionID: string;
        ViewID: string;
        ImageID: string;
        AIContentTemplateID: string;
        AIContentTemplateVersionID: string;
        AIJobID: string;
        /** @description Actor-scoped create key. Reusing it with the same normalized request returns the original job; different input returns 409. */
        IdempotencyKey: string;
        /** @description Exact updated_at value from the latest SOPVersion response; stale revisions return 409. */
        SOPRevision: string;
    };
    requestBodies: {
        UUIDOrder: {
            content: {
                "application/json": {
                    public_ids: string[];
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCaptureSOPs: {
        parameters: {
            query?: {
                category_id?: number;
                /** @description Manager-only lifecycle listing (admin/operator). When true, includes draft-only and archived-only SOPs and every ordered version. Defaults to published-only selection semantics. */
                include_all?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capture SOPs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CaptureSOPSummary"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createCaptureSOP: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCaptureSOPRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCaptureSOP: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sop_id: components["parameters"]["SOPID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capture SOP */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureSOPSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    copySOPVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sop_id: components["parameters"]["SOPID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    source_version_id: string;
                };
            };
        };
        responses: {
            /** @description Copied draft */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getSOPVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SOP version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateSOPVersion: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact updated_at value from the latest SOPVersion response; stale revisions return 409. */
                "X-SOP-Version-Updated-At": components["parameters"]["SOPRevision"];
            };
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionMetadataRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            428: components["responses"]["PreconditionRequired"];
            500: components["responses"]["InternalServerError"];
        };
    };
    addSOPView: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact updated_at value from the latest SOPVersion response; stale revisions return 409. */
                "X-SOP-Version-Updated-At": components["parameters"]["SOPRevision"];
            };
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddViewRequest"];
            };
        };
        responses: {
            /** @description View added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            428: components["responses"]["PreconditionRequired"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteSOPView: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact updated_at value from the latest SOPVersion response; stale revisions return 409. */
                "X-SOP-Version-Updated-At": components["parameters"]["SOPRevision"];
            };
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            428: components["responses"]["PreconditionRequired"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateSOPView: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact updated_at value from the latest SOPVersion response; stale revisions return 409. */
                "X-SOP-Version-Updated-At": components["parameters"]["SOPRevision"];
            };
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewMutation"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            428: components["responses"]["PreconditionRequired"];
            500: components["responses"]["InternalServerError"];
        };
    };
    reorderSOPViews: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact updated_at value from the latest SOPVersion response; stale revisions return 409. */
                "X-SOP-Version-Updated-At": components["parameters"]["SOPRevision"];
            };
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UUIDOrder"];
        responses: {
            /** @description Reordered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            428: components["responses"]["PreconditionRequired"];
            500: components["responses"]["InternalServerError"];
        };
    };
    validateSOPVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    publishSOPVersion: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact updated_at value from the latest SOPVersion response; stale revisions return 409. */
                "X-SOP-Version-Updated-At": components["parameters"]["SOPRevision"];
            };
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
            428: components["responses"]["PreconditionRequired"];
            500: components["responses"]["InternalServerError"];
        };
    };
    archiveSOPVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createSOPReferenceUploadURL: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    file_name: string;
                    content_type: string;
                };
            };
        };
        responses: {
            /** @description SOP reference upload details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPReferenceUploadEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    addSOPReferenceImage: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact updated_at value from the latest SOPVersion response; stale revisions return 409. */
                "X-SOP-Version-Updated-At": components["parameters"]["SOPRevision"];
            };
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddReferenceImageRequest"];
            };
        };
        responses: {
            /** @description Reference image added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            428: components["responses"]["PreconditionRequired"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteSOPReferenceImage: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact updated_at value from the latest SOPVersion response; stale revisions return 409. */
                "X-SOP-Version-Updated-At": components["parameters"]["SOPRevision"];
            };
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
                image_id: components["parameters"]["ImageID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            428: components["responses"]["PreconditionRequired"];
            500: components["responses"]["InternalServerError"];
        };
    };
    reorderSOPReferenceImages: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact updated_at value from the latest SOPVersion response; stale revisions return 409. */
                "X-SOP-Version-Updated-At": components["parameters"]["SOPRevision"];
            };
            path: {
                version_id: components["parameters"]["VersionID"];
                view_id: components["parameters"]["ViewID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UUIDOrder"];
        responses: {
            /** @description Reordered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOPVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            428: components["responses"]["PreconditionRequired"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createPhotoSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePhotoSessionRequest"];
            };
        };
        responses: {
            /** @description Photo session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createAssetUploadURL: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssetUploadRequest"];
            };
        };
        responses: {
            /** @description Capture asset upload details with a signed completion ticket */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetUploadEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    completeAssetUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteAssetRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay; returns the asset previously created by this completion ticket */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedAsset"];
                };
            };
            /** @description Asset completed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedAsset"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listAssetsForReview: {
        parameters: {
            query?: {
                status?: "pending" | "approved" | "rejected";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review assets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AssetReviewItem"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listAssetReviewHierarchy: {
        parameters: {
            query?: {
                status?: "pending" | "approved" | "rejected";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review assets grouped by category and SKU */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AssetReviewCategory"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getOpenAISetting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Masked OpenAI provider setting */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenAISetting"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    putOpenAISetting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenAISettingRequest"];
            };
        };
        responses: {
            /** @description Verified and activated OpenAI provider setting */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenAISetting"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description OpenAI rejected the supplied credential */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    disableOpenAISetting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disabled OpenAI provider setting */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenAISetting"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listAIContentTemplates: {
        parameters: {
            query?: {
                /** @description When true includes draft and archived versions; otherwise returns templates with published versions only. */
                include_all?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AI content templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AIContentTemplate"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createAIContentTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AIContentTemplateMutationRequest"];
            };
        };
        responses: {
            /** @description Created template with its initial draft */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIContentTemplate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAIContentTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: components["parameters"]["AIContentTemplateID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AI content template with ordered versions and slots */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIContentTemplate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    copyAIContentTemplateVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: components["parameters"]["AIContentTemplateID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopyAIContentTemplateVersionRequest"];
            };
        };
        responses: {
            /** @description Copied draft version */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIContentTemplateVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateAIContentTemplateVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["AIContentTemplateVersionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AIContentTemplateMutationRequest"];
            };
        };
        responses: {
            /** @description Updated draft version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIContentTemplateVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    validateAIContentTemplateVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["AIContentTemplateVersionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AITemplateValidationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    publishAIContentTemplateVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["AIContentTemplateVersionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published immutable template version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIContentTemplateVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            /** @description Template validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AITemplateValidationResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    archiveAIContentTemplateVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["AIContentTemplateVersionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived template version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIContentTemplateVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listAIJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AI jobs in newest-first order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AIJob"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createAIJob: {
        parameters: {
            query?: never;
            header: {
                /** @description Actor-scoped create key. Reusing it with the same normalized request returns the original job; different input returns 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAIJobRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay of the existing AI job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIJob"];
                };
            };
            /** @description Reproducible dry-run AI job */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIJob"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            /** @description Selected SKU */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getAIJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["AIJobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AI job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIJob"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
