package ai

import (
	"context"
	"encoding/json"
	"errors"
	"strconv"
	"strings"

	"cargoflow/api/internal/models"
	"github.com/google/uuid"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// ImageExecutor executes the initial immutable turn for an image job item. It
// intentionally persists only the compiled non-binary request; source and
// generated bytes exist only in object storage or process memory.
type ImageExecutor struct {
	db          *gorm.DB
	credentials ActiveCredentialSource
	provider    ImageProvider
	storage     *ImageStorage
	model       string
	clock       Clock
}

func NewImageExecutor(db *gorm.DB, credentials ActiveCredentialSource, provider ImageProvider, storage *ImageStorage, model string) *ImageExecutor {
	if model == "" {
		model = "gpt-5.6"
	}
	return &ImageExecutor{db: db, credentials: credentials, provider: provider, storage: storage, model: model, clock: SystemClock{}}
}

type preparedImageExecution struct {
	execution  models.AIExecution
	turn       models.AIImageTurn
	prompt     CompiledImagePrompt
	job        models.AIJob
	item       models.AIJobItem
	sourceKeys []string
	completed  bool
}

func (e *ImageExecutor) Execute(ctx context.Context, leased LeasedItem) error {
	if e == nil || e.provider == nil || e.storage == nil {
		return errors.New("image executor is unavailable")
	}
	p, err := e.prepare(ctx, leased)
	if err != nil || p.completed {
		return err
	}
	inputs := make([]ImageInput, 0, len(p.sourceKeys))
	for _, key := range p.sourceKeys {
		input, readErr := e.storage.ReadSource(ctx, key)
		if readErr != nil {
			return e.fail(ctx, p, models.AIExecutionFailed, "Approved source image is unavailable", "")
		}
		inputs = append(inputs, input)
	}
	defer func() {
		for i := range inputs {
			clearByteSlice(inputs[i].Bytes)
		}
	}()

	credential, err := e.credentials.DecryptActiveCredential(ctx)
	defer clearBytes(credential.APIKey)
	if err != nil || len(credential.APIKey) == 0 || credential.SettingID == 0 || credential.KeyFingerprint == "" {
		return e.fail(ctx, p, models.AIExecutionFailed, "OpenAI credential is unavailable", "")
	}
	if err := e.dispatch(ctx, leased, p, credential); err != nil {
		return e.fail(ctx, p, models.AIExecutionFailed, "OpenAI dispatch failed before a confirmed call", "")
	}
	response, providerErr := e.provider.Generate(ctx, credential.APIKey, ImageRequest{Prompt: p.prompt, Inputs: inputs, Metadata: map[string]string{"job_id": p.job.PublicID, "job_item_id": p.item.PublicID, "execution_id": p.execution.PublicID}})
	clearBytes(credential.APIKey)
	if providerErr != nil {
		status, safe := imageProviderFailureState(providerErr)
		return e.fail(ctx, p, status, safe, imageProviderRequestID(providerErr))
	}
	defer clearByteSlice(response.ImageBytes)
	if response.ResponseID == "" || response.RequestID == "" || response.Model == "" || response.ImageCallID == "" {
		return e.fail(ctx, p, models.AIExecutionFailed, "OpenAI returned an invalid image response", response.RequestID)
	}
	w, h, dimErr := imageDimensions(p.prompt.ToolConfig.Size)
	if dimErr != nil {
		return e.fail(ctx, p, models.AIExecutionFailed, "Image generation configuration is invalid", response.RequestID)
	}
	stored, err := e.storage.StoreGenerated(ctx, GeneratedImageStoreRequest{JobPublicID: p.job.PublicID, ItemPublicID: p.item.PublicID, TurnPublicID: p.turn.PublicID, CandidateIndex: 1, Bytes: response.ImageBytes, ExpectedWidth: w, ExpectedHeight: h, Persist: func(persistCtx context.Context, object StoredGeneratedImage) error {
		return e.persistResult(persistCtx, p, response, object)
	}})
	if err != nil {
		return e.fail(ctx, p, models.AIExecutionNeedsAttention, "Generated image could not be safely stored", response.RequestID)
	}
	_ = stored
	return nil
}

func (e *ImageExecutor) prepare(ctx context.Context, leased LeasedItem) (preparedImageExecution, error) {
	var result preparedImageExecution
	err := e.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		item, job, version, relationalSlot, err := loadExecutionBindings(tx, leased, e.clock.Now())
		if err != nil {
			return err
		}
		if item.Kind != models.AIContentSlotImage {
			return ErrRealImageGenerationUnsupported
		}
		if _, err := validateDryRunProvenance(job, item, version, relationalSlot); err != nil {
			return err
		}
		var snapshot ProductSnapshotV1
		var slot SlotFacts
		if decodeStrictJSON(job.InputSnapshotJSON, &snapshot) != nil || decodeStrictJSON(item.SlotSnapshotJSON, &slot) != nil {
			return invalidExecutionInput("malformed image prompt snapshot")
		}
		var existing models.AIExecution
		if err := tx.Where("ai_job_item_id = ? AND attempt_number = ?", item.ID, item.AttemptCount).First(&existing).Error; err == nil {
			if existing.Status == models.AIExecutionCompleted {
				result.completed = true
				return nil
			}
			return ErrExecutionNeedsAttention
		} else if !errors.Is(err, gorm.ErrRecordNotFound) {
			return err
		}
		var thread models.AIImageThread
		if err := tx.Where("ai_job_item_id = ?", item.ID).First(&thread).Error; errors.Is(err, gorm.ErrRecordNotFound) {
			thread = models.AIImageThread{PublicID: uuid.NewString(), AIJobItemID: item.ID}
			if err := tx.Create(&thread).Error; err != nil {
				return err
			}
		} else if err != nil {
			return err
		}
		prompt, err := CompileImagePrompt(snapshot, slot, ImageTurnInput{Operation: models.AIExecutionGenerate, ThreadPublicID: thread.PublicID})
		if err != nil {
			return invalidExecutionInput("image prompt compilation failed")
		}
		metadata, err := json.Marshal(prompt)
		if err != nil {
			return err
		}
		turn := models.AIImageTurn{PublicID: uuid.NewString(), AIImageThreadID: thread.ID, Sequence: 1, Operation: models.AIExecutionGenerate, RequestedCandidateCount: 1, Size: prompt.ToolConfig.Size, Quality: prompt.ToolConfig.Quality, Style: imagePromptStyle(prompt), CompiledRequestMetadataJSON: metadata, Status: models.AIImageTurnQueued, ActorID: job.CreatedByID}
		if err := tx.Create(&turn).Error; err != nil {
			return err
		}
		now := e.clock.Now()
		requestConfig, _ := json.Marshal(map[string]any{"model": e.model, "size": prompt.ToolConfig.Size, "quality": prompt.ToolConfig.Quality, "store": false})
		execution := models.AIExecution{PublicID: uuid.NewString(), AIJobItemID: item.ID, AIImageTurnID: &turn.ID, Operation: models.AIExecutionGenerate, Status: models.AIExecutionPreparing, AttemptNumber: item.AttemptCount, L0PolicyVersion: prompt.LayerVersions.L0, L1ProductContextVersion: prompt.LayerVersions.L1, L2TemplateVersionPublicID: prompt.LayerVersions.L2, L3ContentSlotPublicID: prompt.LayerVersions.L3, NormalizedInputJSON: prompt.NormalizedInputJSON, OrderedInputListJSON: prompt.OrderedInputListJSON, CompiledPrompt: prompt.Instructions, CompiledPromptSHA256: prompt.SHA256, UserInstruction: snapshot.UserPreference, Model: e.model, RequestConfigJSON: requestConfig, WorkerID: leased.LeaseOwner, LeaseExpiresAt: item.LeaseExpiresAt, StartedAt: &now}
		if err := tx.Create(&execution).Error; err != nil {
			return err
		}
		var ids []string
		if decodeStrictJSON(item.SelectedInputAssetIDsJSON, &ids) != nil || len(ids) == 0 {
			return invalidExecutionInput("image item requires selected assets")
		}
		var assets []models.Asset
		if err := tx.Where("public_id IN ? AND sk_uid = ? AND review_status = ?", ids, job.SKUID, "approved").Find(&assets).Error; err != nil || len(assets) != len(ids) {
			return invalidExecutionInput("selected source asset is unavailable")
		}
		byID := make(map[string]models.Asset, len(assets))
		for _, asset := range assets {
			byID[asset.PublicID] = asset
		}
		keys := make([]string, 0, len(ids))
		for _, id := range ids {
			asset, ok := byID[id]
			if !ok {
				return invalidExecutionInput("selected source asset mismatch")
			}
			keys = append(keys, asset.ObjectKey)
		}
		result = preparedImageExecution{execution: execution, turn: turn, prompt: prompt, job: job, item: item, sourceKeys: keys}
		return nil
	})
	return result, err
}

func imagePromptStyle(prompt CompiledImagePrompt) string {
	var value struct {
		Request struct {
			Style string `json:"style"`
		} `json:"request"`
	}
	if json.Unmarshal(prompt.NormalizedInputJSON, &value) == nil && value.Request.Style != "" {
		return value.Request.Style
	}
	return "default"
}

func imageDimensions(size string) (int, int, error) {
	parts := strings.Split(size, "x")
	if len(parts) != 2 {
		return 0, 0, errors.New("invalid image size")
	}
	w, e1 := strconv.Atoi(parts[0])
	h, e2 := strconv.Atoi(parts[1])
	if e1 != nil || e2 != nil || w < 1 || h < 1 {
		return 0, 0, errors.New("invalid image size")
	}
	return w, h, nil
}

func (e *ImageExecutor) dispatch(ctx context.Context, leased LeasedItem, p preparedImageExecution, credential ActiveOpenAICredential) error {
	return e.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if _, _, _, _, err := loadExecutionBindings(tx, leased, e.clock.Now()); err != nil {
			return err
		}
		now := e.clock.Now()
		setting := tx.Model(&models.OpenAIProviderSetting{}).Where("id = ? AND provider = ? AND status = ? AND key_fingerprint = ?", credential.SettingID, openAIProvider, "active", credential.KeyFingerprint).Update("last_used_at", now)
		if setting.Error != nil || setting.RowsAffected != 1 {
			return ErrProviderNotActive
		}
		if err := tx.Model(&models.AIExecution{}).Where("id = ? AND status = ?", p.execution.ID, models.AIExecutionPreparing).Updates(map[string]any{"status": models.AIExecutionCallingOpenAI, "openai_provider_setting_id": credential.SettingID, "openai_key_fingerprint": credential.KeyFingerprint}).Error; err != nil {
			return err
		}
		if err := tx.Model(&models.AIImageTurn{}).Where("id = ? AND status = ?", p.turn.ID, models.AIImageTurnQueued).Updates(map[string]any{"status": models.AIImageTurnRunning, "lease_owner": leased.LeaseOwner, "lease_expires_at": p.item.LeaseExpiresAt, "started_at": now}).Error; err != nil {
			return err
		}
		metadata, _ := json.Marshal(map[string]any{"model": e.model, "key_fingerprint": credential.KeyFingerprint, "size": p.prompt.ToolConfig.Size, "quality": p.prompt.ToolConfig.Quality})
		jobID, itemID, executionID := p.job.ID, p.item.ID, p.execution.ID
		return tx.Create(&models.AIAuditEvent{PublicID: uuid.NewString(), EventType: "ai_execution.image_dispatched", EntityType: "ai_execution", EntityPublicID: p.execution.PublicID, AIJobID: &jobID, AIJobItemID: &itemID, AIExecutionID: &executionID, MetadataJSON: metadata}).Error
	})
}

func (e *ImageExecutor) persistResult(ctx context.Context, p preparedImageExecution, response ImageResponse, stored StoredGeneratedImage) error {
	return e.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		var execution models.AIExecution
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&execution, p.execution.ID).Error; err != nil {
			return err
		}
		if execution.Status != models.AIExecutionCallingOpenAI {
			return ErrExecutionNeedsAttention
		}
		result := models.AIImageResult{PublicID: uuid.NewString(), AIImageTurnID: p.turn.ID, AIExecutionID: execution.ID, CandidateIndex: 1, ObjectKey: stored.ObjectKey, MIMEType: stored.MIMEType, Width: stored.Width, Height: stored.Height, ByteCount: stored.ByteCount, SHA256: stored.SHA256, ProviderImageCallID: response.ImageCallID}
		if err := tx.Create(&result).Error; err != nil {
			return err
		}
		now := e.clock.Now()
		if err := tx.Model(&execution).Updates(map[string]any{"status": models.AIExecutionCompleted, "open_ai_response_id": response.ResponseID, "open_ai_request_id": response.RequestID, "model": response.Model, "input_text_tokens": response.Usage.InputTextTokens, "input_image_tokens": response.Usage.InputImageTokens, "output_text_tokens": response.Usage.OutputTextTokens, "output_image_tokens": response.Usage.OutputImageTokens, "total_tokens": response.Usage.TotalTokens, "completed_at": now, "safe_error": ""}).Error; err != nil {
			return err
		}
		// A successfully persisted image proves that the credential can use the
		// configured image tool; keep the settings UI as an operational signal.
		if execution.OpenAIProviderSettingID != nil {
			if err := tx.Model(&models.OpenAIProviderSetting{}).Where("id = ?", *execution.OpenAIProviderSettingID).Update("image_capability_verified_at", now).Error; err != nil {
				return err
			}
		}
		if err := tx.Create(&models.AIUsageLedger{AIExecutionID: execution.ID, Model: response.Model, InputTextTokens: response.Usage.InputTextTokens, InputImageTokens: response.Usage.InputImageTokens, OutputTextTokens: response.Usage.OutputTextTokens, OutputImageTokens: response.Usage.OutputImageTokens, TotalTokens: response.Usage.TotalTokens, Currency: "USD", OpenAIRequestID: response.RequestID}).Error; err != nil {
			return err
		}
		if err := tx.Model(&models.AIImageTurn{}).Where("id = ?", p.turn.ID).Updates(map[string]any{"status": models.AIImageTurnCompleted, "completed_at": now, "lease_owner": "", "lease_expires_at": nil}).Error; err != nil {
			return err
		}
		jobID, itemID, executionID := p.job.ID, p.item.ID, execution.ID
		metadata, _ := json.Marshal(map[string]any{"model": response.Model, "openai_request_id": response.RequestID, "openai_response_id": response.ResponseID, "candidate_count": 1, "usage": response.Usage})
		return tx.Create(&models.AIAuditEvent{PublicID: uuid.NewString(), EventType: "ai_execution.image_completed", EntityType: "ai_execution", EntityPublicID: execution.PublicID, AIJobID: &jobID, AIJobItemID: &itemID, AIExecutionID: &executionID, MetadataJSON: metadata}).Error
	})
}

func (e *ImageExecutor) fail(ctx context.Context, p preparedImageExecution, status models.AIExecutionStatus, safe, requestID string) error {
	return e.db.WithContext(context.WithoutCancel(ctx)).Transaction(func(tx *gorm.DB) error {
		now := e.clock.Now()
		tx.Model(&models.AIExecution{}).Where("id = ?", p.execution.ID).Updates(map[string]any{"status": status, "safe_error": safe, "open_ai_request_id": requestID, "completed_at": now})
		turnStatus := models.AIImageTurnFailed
		if status == models.AIExecutionNeedsAttention {
			turnStatus = models.AIImageTurnNeedsAttention
		}
		tx.Model(&models.AIImageTurn{}).Where("id = ?", p.turn.ID).Updates(map[string]any{"status": turnStatus, "safe_error": safe, "completed_at": now, "lease_owner": "", "lease_expires_at": nil})
		return errors.New(safe)
	})
}

func imageProviderFailureState(err error) (models.AIExecutionStatus, string) {
	switch {
	case errors.Is(err, ErrImageProviderAmbiguousTimeout), errors.Is(err, ErrImageProviderAmbiguousTransport):
		return models.AIExecutionNeedsAttention, "OpenAI call outcome is ambiguous"
	case errors.Is(err, ErrImageProviderAuthentication):
		return models.AIExecutionFailed, "OpenAI authentication failed"
	case errors.Is(err, ErrImageProviderModeration):
		return models.AIExecutionFailed, "OpenAI blocked the image request"
	case errors.Is(err, ErrImageProviderRefusal):
		return models.AIExecutionFailed, "OpenAI refused the image request"
	default:
		return models.AIExecutionFailed, "OpenAI image generation failed"
	}
}
func imageProviderRequestID(err error) string {
	var providerErr *ImageProviderError
	if errors.As(err, &providerErr) {
		return providerErr.RequestID
	}
	return ""
}

var _ ItemExecutor = (*ImageExecutor)(nil)
