package ai

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	"cargoflows/api/internal/models"
	"github.com/google/uuid"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// ImageExecutor executes the initial immutable turn for an image job item. It
// intentionally persists only the compiled non-binary request; source and
// generated bytes exist only in object storage or process memory.
type ImageExecutor struct {
	db          *gorm.DB
	credentials ActiveCredentialSource
	provider    ImageProvider
	storage     *ImageStorage
	model       string
	clock       Clock
}

func NewImageExecutor(db *gorm.DB, credentials ActiveCredentialSource, provider ImageProvider, storage *ImageStorage, model string) *ImageExecutor {
	if model == "" {
		model = "gpt-5.6"
	}
	return &ImageExecutor{db: db, credentials: credentials, provider: provider, storage: storage, model: model, clock: SystemClock{}}
}

type preparedImageExecution struct {
	execution  models.AIExecution
	turn       models.AIImageTurn
	prompt     CompiledImagePrompt
	job        models.AIJob
	item       models.AIJobItem
	sourceKeys []string
	parentKey  string
	maskKey    string
	completed  bool
}

func (e *ImageExecutor) Execute(ctx context.Context, leased LeasedItem) error {
	if e == nil || e.provider == nil || e.storage == nil {
		return errors.New("image executor is unavailable")
	}
	p, err := e.prepare(ctx, leased)
	if err != nil || p.completed {
		return err
	}
	inputs := make([]ImageInput, 0, len(p.sourceKeys))
	if p.parentKey != "" {
		input, readErr := e.storage.ReadGenerated(ctx, p.parentKey)
		if readErr != nil {
			return e.fail(ctx, p, models.AIExecutionFailed, "Selected parent image is unavailable", "")
		}
		inputs = append(inputs, input)
	}
	for _, key := range p.sourceKeys {
		input, readErr := e.storage.ReadSource(ctx, key)
		if readErr != nil {
			return e.fail(ctx, p, models.AIExecutionFailed, "Approved source image is unavailable", "")
		}
		inputs = append(inputs, input)
	}
	defer func() {
		for i := range inputs {
			clearByteSlice(inputs[i].Bytes)
		}
	}()
	var mask *ImageInput
	if p.maskKey != "" {
		value, readErr := e.storage.ReadSource(ctx, p.maskKey)
		if readErr != nil || value.MIMEType != "image/png" {
			return e.fail(ctx, p, models.AIExecutionFailed, "Image edit mask is unavailable", "")
		}
		mask = &value
		defer clearByteSlice(value.Bytes)
	}

	credential, err := e.credentials.DecryptActiveCredential(ctx)
	defer clearBytes(credential.APIKey)
	if err != nil || len(credential.APIKey) == 0 || credential.SettingID == 0 || credential.KeyFingerprint == "" {
		return e.fail(ctx, p, models.AIExecutionFailed, "OpenAI credential is unavailable", "")
	}
	modelSnapshot := decodeJobModelSnapshot(p.job.ModelSnapshotJSON)
	apiMode := configuredImageMode(defaultString(modelSnapshot.ImageAPIMode, credential.ImageAPIMode))
	runtimeModel := configuredModel(modelSnapshot.ImageResponsesModel, configuredModel(credential.ImageResponsesModel, e.model))
	if apiMode == "images" {
		runtimeModel = configuredModel(modelSnapshot.ImageGenerationModel, configuredModel(credential.ImageGenerationModel, DefaultOpenAIImageGenerationModel))
	}
	if mask != nil {
		apiMode = "images"
		runtimeModel = configuredModel(modelSnapshot.ImageGenerationModel, configuredModel(credential.ImageGenerationModel, DefaultOpenAIImageGenerationModel))
	}
	if err := bindExecutionModel(ctx, e.db, &p.execution, runtimeModel); err != nil {
		return e.fail(ctx, p, models.AIExecutionFailed, "OpenAI model selection could not be stored", "")
	}
	if err := bindExecutionAPIMode(ctx, e.db, &p.execution, apiMode); err != nil {
		return e.fail(ctx, p, models.AIExecutionFailed, "OpenAI image API mode could not be stored", "")
	}
	if err := e.dispatch(ctx, leased, p, credential); err != nil {
		return e.fail(ctx, p, models.AIExecutionFailed, "OpenAI dispatch failed before a confirmed call", "")
	}
	providerCtx, cancelProvider := context.WithTimeout(ctx, time.Duration(configuredProviderTimeout(credential.ImageRequestTimeoutSeconds, DefaultOpenAIImageTimeoutSeconds))*time.Second)
	response, providerErr := e.provider.Generate(providerCtx, credential.APIKey, ImageRequest{Model: runtimeModel, APIMode: apiMode, Prompt: p.prompt, Inputs: inputs, Mask: mask, Metadata: map[string]string{"job_id": p.job.PublicID, "job_item_id": p.item.PublicID, "execution_id": p.execution.PublicID}})
	cancelProvider()
	clearBytes(credential.APIKey)
	if providerErr != nil {
		status, safe := imageProviderFailureState(providerErr)
		return e.fail(ctx, p, status, safe, imageProviderRequestID(providerErr))
	}
	defer clearByteSlice(response.ImageBytes)
	if response.ResponseID == "" || response.RequestID == "" || response.Model == "" || response.ImageCallID == "" {
		return e.fail(ctx, p, models.AIExecutionFailed, "OpenAI returned an invalid image response", response.RequestID)
	}
	w, h, dimErr := imageDimensions(p.prompt.ToolConfig.Size)
	if dimErr != nil {
		return e.fail(ctx, p, models.AIExecutionFailed, "Image generation configuration is invalid", response.RequestID)
	}
	stored, err := e.storage.StoreGenerated(ctx, GeneratedImageStoreRequest{JobPublicID: p.job.PublicID, ItemPublicID: p.item.PublicID, TurnPublicID: p.turn.PublicID, CandidateIndex: 1, Bytes: response.ImageBytes, ExpectedWidth: w, ExpectedHeight: h, Persist: func(persistCtx context.Context, object StoredGeneratedImage) error {
		return e.persistResult(persistCtx, p, response, object)
	}})
	if err != nil {
		return e.fail(ctx, p, models.AIExecutionNeedsAttention, "Generated image could not be safely stored", response.RequestID)
	}
	_ = stored
	return nil
}

func bindExecutionAPIMode(ctx context.Context, db *gorm.DB, execution *models.AIExecution, mode string) error {
	mode = configuredImageMode(mode)
	result := db.WithContext(ctx).Model(&models.AIExecution{}).Where("id = ? AND status = ?", execution.ID, models.AIExecutionPreparing).Update("api_mode", mode)
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected != 1 {
		return ErrExecutionNeedsAttention
	}
	execution.APIMode = mode
	return nil
}

func (e *ImageExecutor) prepare(ctx context.Context, leased LeasedItem) (preparedImageExecution, error) {
	var result preparedImageExecution
	err := e.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		item, job, version, relationalSlot, err := loadExecutionBindings(tx, leased, e.clock.Now())
		if err != nil {
			return err
		}
		if item.Kind != models.AIContentSlotImage {
			return ErrRealImageGenerationUnsupported
		}
		if _, err := validateExecutionProvenance(job, item, version, relationalSlot); err != nil {
			return err
		}
		var snapshot ProductSnapshotV1
		var slot SlotFacts
		if decodeStrictJSON(job.InputSnapshotJSON, &snapshot) != nil || decodeStrictJSON(item.SlotSnapshotJSON, &slot) != nil {
			return invalidExecutionInput("malformed image prompt snapshot")
		}
		var existing models.AIExecution
		if err := tx.Where("ai_job_item_id = ? AND attempt_number = ?", item.ID, item.AttemptCount).First(&existing).Error; err == nil {
			if existing.Status == models.AIExecutionCompleted {
				result.completed = true
				return nil
			}
			return ErrExecutionNeedsAttention
		} else if !errors.Is(err, gorm.ErrRecordNotFound) {
			return err
		}
		var thread models.AIImageThread
		if err := tx.Where("ai_job_item_id = ?", item.ID).First(&thread).Error; errors.Is(err, gorm.ErrRecordNotFound) {
			thread = models.AIImageThread{PublicID: uuid.NewString(), AIJobItemID: item.ID}
			if err := tx.Create(&thread).Error; err != nil {
				return err
			}
		} else if err != nil {
			return err
		}
		var turn models.AIImageTurn
		turnErr := tx.Where("ai_image_thread_id = ? AND status = ?", thread.ID, models.AIImageTurnQueued).Order("sequence ASC").First(&turn).Error
		if errors.Is(turnErr, gorm.ErrRecordNotFound) {
			sequence, sequenceErr := nextImageTurnSequence(tx, thread.ID)
			if sequenceErr != nil {
				return sequenceErr
			}
			turn = models.AIImageTurn{PublicID: uuid.NewString(), AIImageThreadID: thread.ID, Sequence: sequence, Operation: models.AIExecutionGenerate, RequestedCandidateCount: 1, Status: models.AIImageTurnQueued, ActorID: job.CreatedByID, ActorSnapshotJSON: job.CreatedBySnapshotJSON}
		} else if turnErr != nil {
			return turnErr
		}
		parentPublicID, parentKey := "", ""
		if turn.ParentResultID != nil {
			var parent models.AIImageResult
			if err := tx.First(&parent, *turn.ParentResultID).Error; err != nil {
				return err
			}
			parentPublicID, parentKey = parent.PublicID, parent.ObjectKey
		}
		oneCandidate := 1
		prompt, err := CompileImagePrompt(snapshot, slot, ImageTurnInput{Operation: turn.Operation, ThreadPublicID: thread.PublicID, ParentThreadPublicID: func() string {
			if turn.ParentResultID != nil {
				return thread.PublicID
			}
			return ""
		}(), ParentResultPublicID: parentPublicID, UserInstruction: turn.UserInstruction, Size: turn.Size, Quality: turn.Quality, Style: turn.Style, CandidateCount: &oneCandidate})
		if err != nil {
			return invalidExecutionInput("image prompt compilation failed")
		}
		metadata, err := json.Marshal(prompt)
		if err != nil {
			return err
		}
		turn.Size, turn.Quality, turn.Style, turn.CompiledRequestMetadataJSON = prompt.ToolConfig.Size, prompt.ToolConfig.Quality, imagePromptStyle(prompt), metadata
		if turn.ID == 0 {
			if err := tx.Create(&turn).Error; err != nil {
				return err
			}
		} else if err := tx.Model(&turn).Updates(map[string]any{"size": turn.Size, "quality": turn.Quality, "style": turn.Style, "compiled_request_metadata_json": metadata}).Error; err != nil {
			return err
		}
		now := e.clock.Now()
		requestConfig, _ := json.Marshal(map[string]any{"model": e.model, "size": prompt.ToolConfig.Size, "quality": prompt.ToolConfig.Quality, "store": false})
		execution := models.AIExecution{PublicID: uuid.NewString(), AIJobItemID: item.ID, AIImageTurnID: &turn.ID, Operation: turn.Operation, Status: models.AIExecutionPreparing, AttemptNumber: item.AttemptCount, L0PolicyVersion: prompt.LayerVersions.L0, L1ProductContextVersion: prompt.LayerVersions.L1, L2TemplateVersionPublicID: prompt.LayerVersions.L2, L3ContentSlotPublicID: prompt.LayerVersions.L3, NormalizedInputJSON: prompt.NormalizedInputJSON, OrderedInputListJSON: prompt.OrderedInputListJSON, CompiledPrompt: prompt.ImagesAPIPrompt(), CompiledPromptSHA256: prompt.SHA256, UserInstruction: turn.UserInstruction, Model: e.model, RequestedModel: e.model, APIMode: "responses", RequestConfigJSON: requestConfig, WorkerID: leased.LeaseOwner, LeaseExpiresAt: item.LeaseExpiresAt, StartedAt: &now}
		if err := tx.Create(&execution).Error; err != nil {
			return err
		}
		var ids []string
		if decodeStrictJSON(item.SelectedInputAssetIDsJSON, &ids) != nil || len(ids) == 0 {
			return invalidExecutionInput("image item requires selected assets")
		}
		var assets []models.Asset
		if err := tx.Where("public_id IN ? AND sk_uid = ? AND review_status = ? AND origin_type <> ?", ids, job.SKUID, "approved", "ai_generated").Find(&assets).Error; err != nil || len(assets) != len(ids) {
			return invalidExecutionInput("selected source asset is unavailable")
		}
		byID := make(map[string]models.Asset, len(assets))
		for _, asset := range assets {
			byID[asset.PublicID] = asset
		}
		productAssets := ImageGenerationProductAssets(snapshot, slot)
		keys := make([]string, 0, len(productAssets))
		for _, fact := range productAssets {
			asset, ok := byID[fact.PublicID]
			if !ok {
				return invalidExecutionInput("selected source asset mismatch")
			}
			keys = append(keys, asset.ObjectKey)
		}
		for _, reference := range snapshot.BrandIcons {
			var stored models.BrandIcon
			if err := tx.Where("public_id = ? AND sha256 = ?", reference.PublicID, reference.SHA256).First(&stored).Error; err != nil || stored.ObjectKey == "" {
				return invalidExecutionInput("frozen brand icon is unavailable")
			}
			keys = append(keys, stored.ObjectKey)
		}
		for _, reference := range snapshot.StructureReferences {
			var stored models.ModelFamilyReferenceAsset
			if err := tx.Where("public_id = ? AND derivative_sha256 = ?", reference.PublicID, reference.DerivativeSHA256).First(&stored).Error; err != nil || stored.DerivativeObjectKey == "" {
				return invalidExecutionInput("frozen structure reference is unavailable")
			}
			keys = append(keys, stored.DerivativeObjectKey)
		}
		for _, reference := range snapshot.StyleReferences {
			var stored models.StyleReferenceGrant
			if err := tx.Where("public_id = ? AND derivative_sha256 = ?", reference.PublicID, reference.DerivativeSHA256).First(&stored).Error; err != nil || stored.DerivativeObjectKey == "" {
				return invalidExecutionInput("frozen style reference is unavailable")
			}
			keys = append(keys, stored.DerivativeObjectKey)
		}
		for _, reference := range imageGenerationBinaryExternalReferences(snapshot.ExternalReferences) {
			var stored models.AIReferenceItem
			if err := tx.Where("public_id = ? AND sha256 = ?", reference.PublicID, reference.SHA256).First(&stored).Error; err != nil || stored.ObjectKey == "" {
				return invalidExecutionInput("frozen external reference is unavailable")
			}
			keys = append(keys, stored.ObjectKey)
		}
		result = preparedImageExecution{execution: execution, turn: turn, prompt: prompt, job: job, item: item, sourceKeys: keys, parentKey: parentKey, maskKey: turn.MaskObjectKey}
		return nil
	})
	return result, err
}

func nextImageTurnSequence(tx *gorm.DB, threadID uint) (int, error) {
	var lastTurn models.AIImageTurn
	err := tx.Where("ai_image_thread_id = ?", threadID).Order("sequence DESC").First(&lastTurn).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return 1, nil
	}
	if err != nil {
		return 0, err
	}
	return lastTurn.Sequence + 1, nil
}

func imagePromptStyle(prompt CompiledImagePrompt) string {
	var value struct {
		Request struct {
			Style string `json:"style"`
		} `json:"request"`
	}
	if json.Unmarshal(prompt.NormalizedInputJSON, &value) == nil && value.Request.Style != "" {
		return value.Request.Style
	}
	return "default"
}

func imageDimensions(size string) (int, int, error) {
	parts := strings.Split(size, "x")
	if len(parts) != 2 {
		return 0, 0, errors.New("invalid image size")
	}
	w, e1 := strconv.Atoi(parts[0])
	h, e2 := strconv.Atoi(parts[1])
	if e1 != nil || e2 != nil || w < 1 || h < 1 {
		return 0, 0, errors.New("invalid image size")
	}
	return w, h, nil
}

func (e *ImageExecutor) dispatch(ctx context.Context, leased LeasedItem, p preparedImageExecution, credential ActiveOpenAICredential) error {
	return e.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if _, _, _, _, err := loadExecutionBindings(tx, leased, e.clock.Now()); err != nil {
			return err
		}
		now := e.clock.Now()
		setting := tx.Model(&models.OpenAIProviderSetting{}).Where("id = ? AND provider = ? AND status = ? AND key_fingerprint = ?", credential.SettingID, openAIProvider, "active", credential.KeyFingerprint).Update("last_used_at", now)
		if setting.Error != nil || setting.RowsAffected != 1 {
			return ErrProviderNotActive
		}
		if err := tx.Model(&models.AIExecution{}).Where("id = ? AND status = ?", p.execution.ID, models.AIExecutionPreparing).Updates(map[string]any{"status": models.AIExecutionCallingOpenAI, "openai_provider_setting_id": credential.SettingID, "openai_key_fingerprint": credential.KeyFingerprint}).Error; err != nil {
			return err
		}
		if err := tx.Model(&models.AIImageTurn{}).Where("id = ? AND status = ?", p.turn.ID, models.AIImageTurnQueued).Updates(map[string]any{"status": models.AIImageTurnRunning, "lease_owner": leased.LeaseOwner, "lease_expires_at": p.item.LeaseExpiresAt, "started_at": now}).Error; err != nil {
			return err
		}
		metadata, _ := json.Marshal(map[string]any{"model": p.execution.Model, "key_fingerprint": credential.KeyFingerprint, "size": p.prompt.ToolConfig.Size, "quality": p.prompt.ToolConfig.Quality})
		jobID, itemID, executionID := p.job.ID, p.item.ID, p.execution.ID
		return tx.Create(&models.AIAuditEvent{PublicID: uuid.NewString(), EventType: "ai_execution.image_dispatched", EntityType: "ai_execution", EntityPublicID: p.execution.PublicID, AIJobID: &jobID, AIJobItemID: &itemID, AIExecutionID: &executionID, MetadataJSON: metadata}).Error
	})
}

func (e *ImageExecutor) persistResult(ctx context.Context, p preparedImageExecution, response ImageResponse, stored StoredGeneratedImage) error {
	return e.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		var execution models.AIExecution
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&execution, p.execution.ID).Error; err != nil {
			return err
		}
		if execution.Status != models.AIExecutionCallingOpenAI {
			return ErrExecutionNeedsAttention
		}
		result := models.AIImageResult{PublicID: uuid.NewString(), AIImageTurnID: p.turn.ID, AIExecutionID: execution.ID, ParentResultID: p.turn.ParentResultID, CandidateIndex: 1, ObjectKey: stored.ObjectKey, MIMEType: stored.MIMEType, Width: stored.Width, Height: stored.Height, ByteCount: stored.ByteCount, SHA256: stored.SHA256, ProviderImageCallID: response.ImageCallID}
		if err := tx.Create(&result).Error; err != nil {
			return err
		}
		now := e.clock.Now()
		if err := tx.Model(&execution).Updates(map[string]any{"status": models.AIExecutionCompleted, "open_ai_response_id": response.ResponseID, "open_ai_request_id": response.RequestID, "model": response.Model, "actual_model": response.Model, "input_text_tokens": response.Usage.InputTextTokens, "cached_input_tokens": response.Usage.CachedInputTokens, "input_image_tokens": response.Usage.InputImageTokens, "output_text_tokens": response.Usage.OutputTextTokens, "output_image_tokens": response.Usage.OutputImageTokens, "reasoning_tokens": response.Usage.ReasoningTokens, "total_tokens": response.Usage.TotalTokens, "service_tier": defaultString(response.ServiceTier, "default"), "completed_at": now, "safe_error": "", "failure_code": ""}).Error; err != nil {
			return err
		}
		execution.ServiceTier = defaultString(response.ServiceTier, "default")
		// A successfully persisted image proves that the credential can use the
		// configured image tool; keep the settings UI as an operational signal.
		if execution.OpenAIProviderSettingID != nil {
			verifiedField := "image_responses_verified_at"
			if execution.APIMode == "images" {
				verifiedField = "image_generation_verified_at"
			}
			if err := tx.Model(&models.OpenAIProviderSetting{}).Where("id = ?", *execution.OpenAIProviderSettingID).Updates(map[string]any{"image_capability_verified_at": now, verifiedField: now}).Error; err != nil {
				return err
			}
		}
		ledger := models.AIUsageLedger{AIExecutionID: execution.ID, Model: response.Model, InputTextTokens: response.Usage.InputTextTokens, CachedInputTokens: response.Usage.CachedInputTokens, InputImageTokens: response.Usage.InputImageTokens, OutputTextTokens: response.Usage.OutputTextTokens, OutputImageTokens: response.Usage.OutputImageTokens, ReasoningTokens: response.Usage.ReasoningTokens, TotalTokens: response.Usage.TotalTokens, Currency: "USD", OpenAIRequestID: response.RequestID}
		if err := tx.Create(&ledger).Error; err != nil {
			return err
		}
		if err := PriceUsageLedger(tx, &ledger, execution); err != nil {
			return err
		}
		if err := tx.Model(&models.AIImageTurn{}).Where("id = ?", p.turn.ID).Updates(map[string]any{"status": models.AIImageTurnCompleted, "completed_at": now, "lease_owner": "", "lease_expires_at": nil}).Error; err != nil {
			return err
		}
		jobID, itemID, executionID := p.job.ID, p.item.ID, execution.ID
		metadata, _ := json.Marshal(map[string]any{"model": response.Model, "openai_request_id": response.RequestID, "openai_response_id": response.ResponseID, "candidate_count": 1, "usage": response.Usage})
		return tx.Create(&models.AIAuditEvent{PublicID: uuid.NewString(), EventType: "ai_execution.image_completed", EntityType: "ai_execution", EntityPublicID: execution.PublicID, AIJobID: &jobID, AIJobItemID: &itemID, AIExecutionID: &executionID, MetadataJSON: metadata}).Error
	})
}

func (e *ImageExecutor) fail(ctx context.Context, p preparedImageExecution, status models.AIExecutionStatus, safe, requestID string) error {
	err := e.db.WithContext(context.WithoutCancel(ctx)).Transaction(func(tx *gorm.DB) error {
		now := e.clock.Now()
		if err := tx.Model(&models.AIExecution{}).Where("id = ?", p.execution.ID).Updates(map[string]any{"status": status, "safe_error": safe, "failure_code": failureCodeForSafeError(safe), "open_ai_request_id": requestID, "completed_at": now}).Error; err != nil {
			return err
		}
		turnStatus := models.AIImageTurnFailed
		if status == models.AIExecutionNeedsAttention {
			turnStatus = models.AIImageTurnNeedsAttention
		}
		return tx.Model(&models.AIImageTurn{}).Where("id = ?", p.turn.ID).Updates(map[string]any{"status": turnStatus, "safe_error": safe, "completed_at": now, "lease_owner": "", "lease_expires_at": nil}).Error
	})
	if err != nil {
		return err
	}
	return errors.New(safe)
}

func imageProviderFailureState(err error) (models.AIExecutionStatus, string) {
	switch {
	case errors.Is(err, ErrImageProviderAmbiguousTimeout):
		return models.AIExecutionNeedsAttention, "OpenAI image request timed out after it was sent; no response was received"
	case errors.Is(err, ErrImageProviderAmbiguousTransport):
		var providerErr *ImageProviderError
		if errors.As(err, &providerErr) && providerErr.StatusCode >= 500 {
			return models.AIExecutionNeedsAttention, fmt.Sprintf("OpenAI image API returned HTTP %d before a result was confirmed", providerErr.StatusCode)
		}
		return models.AIExecutionNeedsAttention, "Connection to OpenAI was interrupted after the image request was sent; no response was received"
	case errors.Is(err, ErrImageProviderAuthentication):
		return models.AIExecutionFailed, "OpenAI authentication failed"
	case errors.Is(err, ErrImageProviderRateLimit):
		return models.AIExecutionFailed, "OpenAI rate limit was reached"
	case errors.Is(err, ErrImageProviderPromptTooLong):
		return models.AIExecutionFailed, "Image prompt exceeds OpenAI's 32,000-character limit"
	case errors.Is(err, ErrImageProviderInvalidRequest):
		return models.AIExecutionFailed, "OpenAI rejected one or more image request parameters"
	case errors.Is(err, ErrImageProviderModeration):
		return models.AIExecutionFailed, "OpenAI blocked the image request"
	case errors.Is(err, ErrImageProviderRefusal):
		return models.AIExecutionFailed, "OpenAI refused the image request"
	default:
		return models.AIExecutionFailed, "OpenAI image generation failed"
	}
}
func imageProviderRequestID(err error) string {
	var providerErr *ImageProviderError
	if errors.As(err, &providerErr) {
		return providerErr.RequestID
	}
	return ""
}

var _ ItemExecutor = (*ImageExecutor)(nil)
