package ai

// ImageStyleCatalog is intentionally keyed by stable identifiers stored in
// published template configuration. The instructions are expanded only while
// compiling a provider request so UI labels never become prompt semantics.
var ImageStyleCatalog = map[string]string{
	"clean_white_background": "Medium: photorealistic ecommerce studio photograph. Background: seamless pure white. Lighting: soft, even, neutral studio light with a subtle grounding shadow. Composition: centered, crisp-edged, product dominant. Allowed environment/props: none unless the slot requires them. Exclusions: no decorative clutter, text, extra products, identity changes, or invented details.",
	"soft_studio":            "Medium: photorealistic studio photograph. Background: quiet neutral gradient. Lighting: large diffused softboxes with gentle dimensional shadows. Composition: balanced and product dominant. Allowed environment/props: restrained neutral plinth only. Exclusions: no labels or geometry changes, extra products, unsupported claims, or busy decoration.",
	"high_key_airy":          "Medium: high-key photorealistic product photograph. Background: off-white and airy. Lighting: bright diffuse illumination with soft readable shadows. Composition: uncluttered with generous negative space. Allowed environment/props: minimal pale surface. Exclusions: no overexposure that hides product details, identity changes, extra products, or unsupported text.",
	"warm_neutral":           "Medium: photorealistic commercial product photograph. Background: warm beige and taupe studio setting. Lighting: soft warm diffused light with restrained shadows. Composition: calm and product dominant. Allowed environment/props: subtle natural-material accents that do not touch or obscure the product. Exclusions: no source-reference products, identity changes, invented materials, or unsupported lifestyle claims.",
	"premium_dark":           "Medium: premium photorealistic studio photograph. Background: charcoal or black. Lighting: controlled key and rim light with deep but readable shadows and precise highlights. Composition: product dominant with intentional negative space. Allowed environment/props: a restrained dark plinth. Exclusions: no loss of labels, cutouts, edges, color accuracy, or visible structure; no extra products or text.",
	"luxury_editorial":       "Medium: luxury editorial product photograph. Background: refined neutral surfaces. Lighting: dramatic but physically accurate studio lighting. Composition: magazine-grade, product dominant, intentional negative space. Allowed environment/props: one or two restrained premium surfaces. Exclusions: no invented branding, jewels, package upgrades, extra products, identity changes, or implied higher specifications.",
	"minimal_gradient":       "Medium: clean commercial product photograph. Background: smooth minimal color gradient. Lighting: soft neutral studio light. Composition: simple centered geometry with ample negative space. Allowed environment/props: none. Exclusions: no decorative clutter, extra products, text, identity changes, or invented visible details.",
	"bold_color_block":       "Medium: photorealistic commercial product photograph. Background: saturated geometric color-blocked surfaces. Lighting: crisp directional studio light that preserves accurate product color. Composition: bold negative space with the product dominant. Allowed environment/props: abstract color planes only. Exclusions: no recoloring the product, foreign logos, extra products, text, or copied reference-product design.",
	"vibrant_pop":            "Medium: energetic photorealistic advertising photograph. Background: bright harmonious color field. Lighting: lively clean studio light with clear subject separation. Composition: playful but product first. Allowed environment/props: a few generic abstract shapes that cannot be mistaken for included accessories. Exclusions: no product recoloring, extra products, foreign brands, unsupported claims, or identity changes.",
	"pastel_soft":            "Medium: soft pastel commercial product photograph. Background: muted harmonious pastel field. Lighting: gentle diffuse light with rounded shadows. Composition: calm, uncluttered, product focused. Allowed environment/props: minimal abstract forms. Exclusions: no product recoloring, source-reference products, invented accessories, text, or geometry changes.",
	"natural_daylight":       "Medium: realistic lifestyle product photograph. Background: relevant everyday setting kept secondary. Lighting: natural window daylight with believable shadows. Composition: product clearly dominant and unobscured. Allowed environment/props: generic context objects only when consistent with supported use. Exclusions: no other product as subject, foreign device or accessory inheritance, unsupported capability, identity changes, or hidden cutouts and labels.",
	"cozy_home":              "Medium: realistic warm home lifestyle photograph. Background: tidy, relatable interior with natural textures. Lighting: soft ambient and window light. Composition: exact product prominent and unobscured. Allowed environment/props: generic home accents that do not imply package contents. Exclusions: no people using unsupported functions, other products as subject, foreign devices, identity changes, or invented accessories.",
	"modern_urban":           "Medium: realistic modern urban lifestyle photograph. Background: restrained concrete, glass, or metal architecture. Lighting: cool natural daylight with accurate product color. Composition: clean lines and a product-dominant frame. Allowed environment/props: generic architectural surfaces only. Exclusions: no other product as subject, foreign branding, unsupported outdoor performance, identity changes, or invented accessories.",
	"outdoor_active":         "Medium: realistic outdoor lifestyle photograph. Background: believable, non-hazardous outdoor context. Lighting: natural sunlight with controlled readable shadows. Composition: energetic while the exact product stays dominant and unobscured. Allowed environment/props: generic terrain or activity context only when supported. Exclusions: no water, impact, extreme weather, speed, durability, protection, or performance implication unless explicitly supported; no foreign product, device, accessory, or identity inheritance.",
	"flat_lay":               "Medium: editorial top-down product photograph. Background: clean single surface. Lighting: soft directional light with controlled shadows. Composition: carefully spaced flat lay with the target product dominant. Allowed environment/props: only generic relevant objects that cannot be mistaken for package contents. Exclusions: no extra sellable products, foreign brands, unsupported accessories, product redesign, or obscured labels and openings.",
	"macro_material":         "Medium: photorealistic macro detail photograph. Background: neutral and defocused. Lighting: controlled highlights revealing only visible surface qualities. Composition: close crop of an actually visible target-SKU area with precise focus. Allowed environment/props: none. Exclusions: do not infer microscopic texture, internal layers, material composition, hidden construction, dimensions, or performance; do not change geometry, finish, color, or identity.",
	"technical_3d":           "Medium: precise photorealistic technical 3D-style render of the externally visible target product. Background: clean neutral technical studio. Lighting: physically plausible controlled studio light. Composition: accurate product-dominant view. Allowed environment/props: neutral ground plane only. Exclusions: no exploded view, cross-section, transparent shell, internal components, unseen backside details, new seams, ports, labels, accessories, or geometry; source images and facts remain authoritative.",
	"isometric_illustration": "Medium: clean commercial isometric illustration derived strictly from visible target-SKU geometry and colors. Background: simple neutral field. Lighting: consistent soft illustrative shading. Composition: restrained product-dominant isometric view. Allowed environment/props: simple abstract ground plane. Exclusions: no invented faces, openings, components, internals, labels, accessories, or source-reference product traits; if a face is not evidenced, keep it unassertive rather than fabricate detail.",
	"clean_infographic":      "Medium: clean ecommerce infographic layout using a faithful target-product image. Background: simple high-contrast field. Lighting: preserve the source-faithful product rendering. Composition: product dominant with structured text-safe callout areas and clear hierarchy. Allowed environment/props: lines and generic icons only when the slot requires them. Exclusions: no unsupported claims, measurements, badges, certifications, comparisons, ratings, invented callout text, hidden-structure diagrams, or product identity changes.",
	"seasonal_campaign":      "Medium: photorealistic seasonal campaign photograph. Background: restrained, culturally neutral seasonal setting. Lighting: polished commercial light with accurate product color. Composition: uncluttered and product dominant. Allowed environment/props: a few generic seasonal accents that cannot be mistaken for package contents. Exclusions: no religious or cultural claims, foreign brands, other products as subject, invented bundles, text, or identity changes.",
}

func imageStyleInstruction(style string) string {
	if instruction, ok := ImageStyleCatalog[style]; ok {
		return instruction
	}
	return style
}
