"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, Copy, GalleryVerticalEnd, LoaderCircle, Pencil, Plus, RotateCcw } from "lucide-react";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { apiRequest } from "@/lib/api";
import { useLanguage } from "@/lib/i18n";

type Category={id:number;name:string;name_en:string};
type Item={public_id:string;purpose:"visual_style"|"usage_effect"|"copy_inspiration"};
type Version={public_id:string;version_number:number;name_zh:string;name_en:string;description_zh:string;description_en:string;status:"draft"|"published"|"archived";items:Item[]};
type ReferenceSOP={public_id:string;category_id:number;category:Category;versions:Version[]};
const selectClass="min-h-11 rounded-md border border-border bg-card px-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20";

export default function AIReferenceSOPsPage(){
 const {language}=useLanguage(),zh=language==="zh",qc=useQueryClient();
 const [showCreate,setShowCreate]=useState(false),[createCategory,setCreateCategory]=useState(""),[filterCategory,setFilterCategory]=useState(""),[status,setStatus]=useState("all"),[purpose,setPurpose]=useState("all");
 const [nameZH,setNameZH]=useState(""),[nameEN,setNameEN]=useState(""),[descriptionZH,setDescriptionZH]=useState(""),[descriptionEN,setDescriptionEN]=useState("");
 const categories=useQuery({queryKey:["categories"],queryFn:()=>apiRequest<{data:Category[]}>("/categories")});
 const query=useQuery({queryKey:["ai-reference-sops","all"],queryFn:()=>apiRequest<{data:ReferenceSOP[]}>("/ai-reference-sops?include_all=true")});
 const refresh=()=>qc.invalidateQueries({queryKey:["ai-reference-sops"]});
 const create=useMutation({mutationFn:()=>apiRequest<ReferenceSOP>("/ai-reference-sops",{method:"POST",body:JSON.stringify({category_id:Number(createCategory),name_zh:nameZH,name_en:nameEN,description_zh:descriptionZH,description_en:descriptionEN})}),onSuccess:(sop)=>{setShowCreate(false);window.location.assign(`/ai-reference-sops/${sop.public_id}/versions/${sop.versions[0].public_id}`)}});
 const copy=useMutation({mutationFn:({sop,version}:{sop:string;version:string})=>apiRequest<Version>(`/ai-reference-sops/${sop}/versions`,{method:"POST",body:JSON.stringify({source_version_id:version})}),onSuccess:(version,input)=>window.location.assign(`/ai-reference-sops/${input.sop}/versions/${version.public_id}`)});
 const transition=useMutation({mutationFn:({version,action}:{version:string;action:"archive"|"restore"})=>apiRequest(`/ai-reference-sop-versions/${version}/${action}`,{method:"POST"}),onSuccess:refresh});
 const filtered=(query.data?.data??[]).map(sop=>({...sop,versions:sop.versions.filter(v=>(status==="all"||v.status===status)&&(purpose==="all"||v.items.some(i=>i.purpose===purpose)))})).filter(s=>s.versions.length&&(filterCategory===""||s.category_id===Number(filterCategory)));
 function submit(e:FormEvent){e.preventDefault();if(createCategory&&nameZH.trim()&&nameEN.trim())create.mutate()}
 return <div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-col gap-4 border-b border-border pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.14em] text-primary"><GalleryVerticalEnd className="h-4 w-4"/>CargoFlows · AI</p><h1 className="text-2xl font-semibold">{zh?"AI 参考 SOP":"AI reference SOPs"}</h1><p className="mt-1 max-w-2xl text-sm text-muted-foreground">{zh?"按商品分类管理外部风格、套机效果和卖点表达参考。它们只提供灵感，不构成目标 SKU 事实。":"Manage category-level style, usage-effect, and copy inspiration. References never establish target-SKU facts."}</p></div><Button className="min-h-11" onClick={()=>setShowCreate(v=>!v)}><Plus className="h-4 w-4"/>{zh?"新建参考 SOP":"New reference SOP"}</Button></header>
 {showCreate?<Card><CardHeader><CardTitle>{zh?"创建草稿":"Create draft"}</CardTitle></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-2" onSubmit={submit}><Field label={zh?"商品分类":"Product category"} id="reference-category"><select className={`${selectClass} w-full`} id="reference-category" required value={createCategory} onChange={e=>setCreateCategory(e.target.value)}><option value="">{zh?"请选择":"Choose"}</option>{categories.data?.data.map(c=><option key={c.id} value={c.id}>{zh?c.name:c.name_en||c.name}</option>)}</select></Field><div/><Field label={zh?"中文名称":"Chinese name"} id="reference-name-zh"><Input id="reference-name-zh" required value={nameZH} onChange={e=>setNameZH(e.target.value)}/></Field><Field label={zh?"英文名称":"English name"} id="reference-name-en"><Input id="reference-name-en" required value={nameEN} onChange={e=>setNameEN(e.target.value)}/></Field><Field label={zh?"中文说明":"Chinese description"} id="reference-description-zh"><Textarea id="reference-description-zh" value={descriptionZH} onChange={e=>setDescriptionZH(e.target.value)}/></Field><Field label={zh?"英文说明":"English description"} id="reference-description-en"><Textarea id="reference-description-en" value={descriptionEN} onChange={e=>setDescriptionEN(e.target.value)}/></Field>{create.isError?<p className="text-sm text-danger md:col-span-2" role="alert">{zh?"创建失败，请检查内容后重试。":"Creation failed. Check the fields and retry."}</p>:null}<div className="flex justify-end md:col-span-2"><Button disabled={create.isPending||!createCategory||!nameZH.trim()||!nameEN.trim()}>{create.isPending?<LoaderCircle className="h-4 w-4 animate-spin motion-reduce:animate-none"/>:<Plus className="h-4 w-4"/>}{zh?"创建并编辑":"Create and edit"}</Button></div></form></CardContent></Card>:null}
 <div className="grid gap-3 rounded-lg border border-border bg-card p-4 sm:grid-cols-3"><Field id="filter-category" label={zh?"分类":"Category"}><select className={`${selectClass} w-full`} id="filter-category" value={filterCategory} onChange={e=>setFilterCategory(e.target.value)}><option value="">{zh?"全部分类":"All categories"}</option>{categories.data?.data.map(c=><option key={c.id} value={c.id}>{zh?c.name:c.name_en||c.name}</option>)}</select></Field><Field id="filter-status" label={zh?"状态":"Status"}><select className={`${selectClass} w-full`} id="filter-status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{zh?"全部状态":"All statuses"}</option><option value="draft">{zh?"草稿":"Draft"}</option><option value="published">{zh?"已发布":"Published"}</option><option value="archived">{zh?"已归档":"Archived"}</option></select></Field><Field id="filter-purpose" label={zh?"用途":"Purpose"}><select className={`${selectClass} w-full`} id="filter-purpose" value={purpose} onChange={e=>setPurpose(e.target.value)}><option value="all">{zh?"全部用途":"All purposes"}</option><option value="visual_style">{zh?"视觉风格":"Visual style"}</option><option value="usage_effect">{zh?"使用效果":"Usage effect"}</option><option value="copy_inspiration">{zh?"文案灵感":"Copy inspiration"}</option></select></Field></div>
 {query.isLoading?<p className="flex min-h-40 items-center justify-center gap-2 text-sm text-muted-foreground" role="status"><LoaderCircle className="h-4 w-4 animate-spin motion-reduce:animate-none"/>{zh?"正在载入…":"Loading…"}</p>:null}{query.isError?<p className="rounded-lg border border-danger/30 bg-danger/5 p-4 text-sm text-danger" role="alert">{zh?"无法载入参考 SOP。":"Could not load reference SOPs."}</p>:null}{!query.isLoading&&!filtered.length?<Card><CardContent className="py-12 text-center text-sm text-muted-foreground">{zh?"当前筛选条件下没有参考 SOP。":"No reference SOPs match these filters."}</CardContent></Card>:null}
 <div className="grid gap-4">{filtered.map(sop=><Card key={sop.public_id}><CardHeader><CardTitle>{zh?sop.category.name:sop.category.name_en||sop.category.name}</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2">{sop.versions.map(version=><article className="rounded-lg border border-border p-4" key={version.public_id}><div className="flex items-center justify-between gap-3"><div><p className="font-semibold">{zh?version.name_zh:version.name_en} · V{version.version_number}</p><p className="mt-1 text-xs text-muted-foreground">{version.items.length} {zh?"项参考":"references"}</p></div><Status value={version.status} zh={zh}/></div><p className="mt-3 line-clamp-2 text-sm text-muted-foreground">{zh?version.description_zh:version.description_en}</p><div className="mt-4 flex flex-wrap gap-2">{version.status==="draft"?<Button asChild size="sm" variant="secondary"><Link href={`/ai-reference-sops/${sop.public_id}/versions/${version.public_id}`}><Pencil className="h-4 w-4"/>{zh?"编辑草稿":"Edit draft"}</Link></Button>:null}{version.status==="published"?<><Button size="sm" variant="secondary" onClick={()=>copy.mutate({sop:sop.public_id,version:version.public_id})}><Copy className="h-4 w-4"/>{zh?"复制新版本":"Copy version"}</Button><Button size="sm" variant="danger" onClick={()=>window.confirm(zh?"归档后将不再出现在新任务中，继续？":"Archive this version?")&&transition.mutate({version:version.public_id,action:"archive"})}><Archive className="h-4 w-4"/>{zh?"归档":"Archive"}</Button></>:null}{version.status==="archived"?<Button size="sm" variant="secondary" onClick={()=>transition.mutate({version:version.public_id,action:"restore"})}><RotateCcw className="h-4 w-4"/>{zh?"恢复":"Restore"}</Button>:null}</div></article>)}</div></CardContent></Card>)}</div></div>
}
function Field({id,label,children}:{id:string;label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label htmlFor={id}>{label}</Label>{children}</div>}
function Status({value,zh}:{value:Version["status"];zh:boolean}){const cls=value==="published"?"border-success/30 bg-success/5 text-success":value==="draft"?"border-warning/30 bg-warning/5 text-warning":"border-border bg-muted text-muted-foreground";const label=value==="published"?(zh?"已发布":"Published"):value==="draft"?(zh?"草稿":"Draft"):(zh?"已归档":"Archived");return <span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${cls}`}>{label}</span>}
