"use client";
/* Authenticated private previews intentionally bypass the Next image optimizer. */
/* eslint-disable @next/next/no-img-element */

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowDown, ArrowLeft, ArrowUp, ImagePlus, Power, PowerOff } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useState } from "react";
import { apiRequest, authenticatedMediaURL } from "@/lib/api";
import { useLanguage } from "@/lib/i18n";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";

type Brand={public_id:string;name:string}; type Icon={public_id:string;name:string;notes:string;media_url:string;width:number;height:number;byte_count:number;sort_order:number;status:"active"|"disabled"};
type UploadEnvelope={upload_url:string;completion_token:string;headers:{"content-type":string}};

export default function BrandDetailPage(){
 const {language}=useLanguage(); const zh=language==="zh"; const {id}=useParams<{id:string}>(); const qc=useQueryClient(); const [files,setFiles]=useState<File[]>([]); const [notes,setNotes]=useState("");
 const brands=useQuery({queryKey:["brands"],queryFn:()=>apiRequest<{data:Brand[]}>("/brands")}); const icons=useQuery({queryKey:["brand-icons",id],queryFn:()=>apiRequest<{data:Icon[]}>(`/brands/${id}/icons`)}); const brand=brands.data?.data.find((b)=>b.public_id===id);
 const upload=useMutation({mutationFn:async()=>{for(const file of files){const envelope=await apiRequest<UploadEnvelope>(`/brands/${id}/icons/upload-url`,{method:"POST",body:JSON.stringify({file_name:file.name,content_type:file.type})}); const response=await fetch(envelope.upload_url,{method:"PUT",headers:envelope.headers,body:file}); if(!response.ok)throw new Error("upload failed"); await apiRequest(`/brands/${id}/icons`,{method:"POST",body:JSON.stringify({completion_token:envelope.completion_token,name:file.name.replace(/\.[^.]+$/,"").replace(/[-_]+/g," "),notes:notes.trim()})});}},onSuccess:async()=>{setFiles([]);setNotes("");await qc.invalidateQueries({queryKey:["brand-icons",id]});}});
 const toggle=useMutation({mutationFn:(icon:Icon)=>apiRequest(`/brands/${id}/icons/${icon.public_id}`,{method:"PATCH",body:JSON.stringify({status:icon.status==="active"?"disabled":"active"})}),onSuccess:()=>qc.invalidateQueries({queryKey:["brand-icons",id]})});
 const reorder=useMutation({mutationFn:(next:Icon[])=>apiRequest(`/brands/${id}/icon-order`,{method:"PUT",body:JSON.stringify({icon_ids:next.map((icon)=>icon.public_id)})}),onSuccess:()=>qc.invalidateQueries({queryKey:["brand-icons",id]})});
 const values=icons.data?.data??[]; function move(index:number,delta:number){const target=index+delta;if(target<0||target>=values.length)return;const next=[...values];[next[index],next[target]]=[next[target],next[index]];reorder.mutate(next);}
 return <div className="space-y-6"><header><Button asChild variant="ghost"><Link href="/brands"><ArrowLeft className="h-4 w-4"/>{zh?"返回品牌":"Back to brands"}</Link></Button><div className="mt-4 flex flex-wrap items-end justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-primary">Brand identity board</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-navy sm:text-4xl">{brand?.name??(zh?"品牌":"Brand")}</h1><p className="mt-2 text-sm text-muted-foreground">{zh?"最多启用 8 个标识。结构必须忠实，颜色可随生成风格调整。":"Up to 8 active marks. Structure stays faithful; color may adapt to each generation style."}</p></div><Badge variant="neutral">{values.filter((icon)=>icon.status==="active").length} / 8 {zh?"启用":"active"}</Badge></div></header>
 <section className="grid gap-4 rounded-xl border border-border bg-card p-5 shadow-[var(--shadow-sm)] lg:grid-cols-[1fr_280px_auto] lg:items-end"><label className="block text-sm font-medium">{zh?"品牌图标（可多选）":"Brand marks (multiple)"}<Input accept="image/png,image/jpeg,image/webp" className="mt-2" multiple onChange={(e)=>setFiles(Array.from(e.target.files??[]))} type="file"/></label><label className="block text-sm font-medium">{zh?"共同备注（可选）":"Shared notes (optional)"}<Textarea className="mt-2 min-h-10" maxLength={500} onChange={(e)=>setNotes(e.target.value)} value={notes}/></label><Button disabled={!files.length||upload.isPending} onClick={()=>upload.mutate()}><ImagePlus className="h-4 w-4"/>{zh?`上传 ${files.length||""} 个图标`:`Upload ${files.length||""} marks`}</Button></section>
 {upload.isError||toggle.isError?<p className="rounded-md border border-danger/30 bg-danger/5 p-3 text-sm text-danger" role="alert">{zh?"操作失败。请检查格式、5 MB 限制和启用数量。":"Operation failed. Check format, the 5 MB limit, and active count."}</p>:null}
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{values.map((icon,index)=><article className={`overflow-hidden rounded-xl border bg-card shadow-[var(--shadow-sm)] ${icon.status==="active"?"border-border":"border-border opacity-60"}`} key={icon.public_id}><div className="grid aspect-[4/3] place-items-center bg-[linear-gradient(45deg,#f2f5f7_25%,transparent_25%),linear-gradient(-45deg,#f2f5f7_25%,transparent_25%),linear-gradient(45deg,transparent_75%,#f2f5f7_75%),linear-gradient(-45deg,transparent_75%,#f2f5f7_75%)] bg-[length:20px_20px] bg-[position:0_0,0_10px,10px_-10px,-10px_0px] p-6"><img alt={icon.name} className="max-h-full max-w-full object-contain" src={authenticatedMediaURL(icon.media_url)}/></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-navy">{icon.name}</h2><p className="mt-1 text-xs text-muted-foreground">{icon.width} × {icon.height} · {(icon.byte_count/1024).toFixed(0)} KB</p></div><Badge variant={icon.status==="active"?"success":"neutral"}>{icon.status}</Badge></div>{icon.notes?<p className="mt-3 text-xs leading-5 text-muted-foreground">{icon.notes}</p>:null}<div className="mt-4 flex gap-2"><Button aria-label={zh?"上移":"Move up"} disabled={index===0||reorder.isPending} onClick={()=>move(index,-1)} size="icon" variant="ghost"><ArrowUp className="h-4 w-4"/></Button><Button aria-label={zh?"下移":"Move down"} disabled={index===values.length-1||reorder.isPending} onClick={()=>move(index,1)} size="icon" variant="ghost"><ArrowDown className="h-4 w-4"/></Button><Button className="ml-auto" disabled={toggle.isPending} onClick={()=>toggle.mutate(icon)} size="sm" variant="outline">{icon.status==="active"?<PowerOff className="h-4 w-4"/>:<Power className="h-4 w-4"/>}{icon.status==="active"?(zh?"停用":"Disable"):(zh?"启用":"Enable")}</Button></div></div></article>)}</section>
 {!icons.isLoading&&!values.length?<div className="rounded-xl border border-dashed border-border p-12 text-center text-sm text-muted-foreground">{zh?"上传主标、横版或其他品牌标识版本。":"Upload a primary, horizontal, or alternate brand mark."}</div>:null}</div>;
}
